INSERT INTO shopping_item (name, category, description, active) VALUES
('Kartoffeln', 'REWE', '1kg', true),
('Äpfel', 'REWE', '3 Stück', true),
('Birnen', 'REWE', 'vergleiche mit Äpfel', false),
('Bananen', 'REWE', '2kg', true),
('Eier', 'REWE', '10 Stück', true),
('Käse', 'REWE', 'Schweizer Käse aus der Schweiz', false),
('Milch', 'REWE', '1 Liter', true),
('Schokolade', 'REWE', '3kg', true),
('Brot', 'REWE', 'Semmeln, Brezn, Brot', true),
('Karotten', 'REWE', '1kg', true),
('Sellerie', 'REWE', '1kg', true),
('Pomelo', 'REWE', '3 Stück', true),
('Nudeln', 'REWE', 'Es gibt Pasta! Basta!', false),
('Pizza', 'REWE', 'Kühlpizza', true),
('Fischstäbchen', 'REWE', 'Phi-Stäbchen', true),
('Burger', 'REWE', 'Patties & Buns', false),
('Scheibenkäse', 'REWE', 'Oh Scheibe', true),
('Ketchup', 'REWE', '3kg', true),
('Senf', 'REWE', '3000 Gläser', true);
